# Spring Boot Configuration
spring.application.name=DOSW-Library
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=postgres
spring.datasource.password=isa1805fl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# SQL Initialization
spring.sql.init.mode=never

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

#MongoDB Configuration
mongodb+srv://root:mongo12345@cluster0.ygomb7z.mongodb.net/?appName=Cluster0